# Generated by Django 4.2.2 on 2024-02-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=250)),
                ('poster_img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('release_date', models.DateField()),
                ('actors', models.CharField(max_length=250)),
                ('category', models.TextField()),
                ('ylink', models.URLField()),
            ],
        ),
    ]
