# Generated by Django 4.2.2 on 2024-02-14 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finaltaskapp', '0002_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finaltaskapp.category'),
        ),
    ]
