# Generated by Django 4.2.2 on 2024-02-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finaltaskapp', '0003_alter_movies_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='category',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
